name: 'Elixir for Dart Analyzer'
author: 'blendthink'
description: 'Tool for commenting `dart analyze` results to GitHub PullRequest.'
branding:
  icon: alert-circle
  color: blue

inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT). defaults to `github.token`.'
    required: false
    default: ${{ github.token }}
  dir:
    description: 'Directory to run the `dart analyze`. defaults to `./`.'
    required: false
    default: ./

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        dart pub global activate elixir
        elixir run \
          --repo=${{ github.repository }} \
          --num=${{ github.event.pull_request.number }} \
          --base=${{ github.base_ref }} \
          --head=${{ github.head_ref }} \
          --dir=${{ inputs.dir }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}