name: 'sign'
author: 'blendthink'
description: 'Tool for commenting `dart analyze` results to GitHub PullRequest.'
branding:
  icon: alert-circle
  color: blue

inputs:
  aaa:
    description: ''
    required: true
    default: ''
  bbb:
    description: ''
    required: true
    default: ''

outputs:
  ccc:
    value: ''
    description: ''

runs:
  using: composite
  steps:
    - name: aaa
      shell: bash
      run: |

    - name: bbb
      shell: bash
      run: |