targets:
  $default:
    sources:
      exclude:
        - "example/**"
        - "bin/**"
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - non_constant_identifier_names
      mockito|mockBuilder:
        generate_for:
          include:
            - "test/**.dart"
          exclude:
            - "test/**.mocks.dart"
