name: elixir
description: Tool for commenting `dart analyze` results to GitHub PullRequest.
version: 1.0.0
homepage: https://github.com/blendthink/elixir
repository: https://github.com/blendthink/elixir
documentation: https://github.com/blendthink/elixir
issue_tracker: https://github.com/blendthink/elixir/issues

executables:
  elixir:

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: ^2.3.1
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  path: ^1.8.2
  pubspec_parse: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  lints: ^2.0.0
  mockito: ^5.2.0
  pubspec_builder: ^1.0.0
  test: ^1.16.0
