name: "analyze"
on:
  pull_request:
    paths:
      - 'example'

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/dart-lang/setup-dart
      - uses: dart-lang/setup-dart@v1

      # https://github.com/blendthink/elixir
      - uses: blendthink/elixir@v1
        with:
          dir: 'example'